"""querysales core schema

Revision ID: 6c7f6e87625b
Revises: b7c8d9e0f1a2
Create Date: 2026-09-04 08:37:57.506768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6c7f6e87625b'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector BEFORE creating tables that use the vector type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_user_id'), 'knowledge_documents', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_index('ix_leads_user_status', 'leads', ['user_id', 'status'], unique=False)
    op.create_table('user_email_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_config_user_id'), 'user_email_config', ['user_id'], unique=True)
    op.create_table('user_embedding_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_embedding_config_user_id'), 'user_embedding_config', ['user_id'], unique=True)
    op.create_table('user_llm_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_llm_config_user_id'), 'user_llm_config', ['user_id'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(1536), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_user_id'), 'knowledge_chunks', ['user_id'], unique=False)
    # IVFFlat index for cosine similarity search (autogenerate cannot produce USING clauses).
    op.execute(
        "CREATE INDEX IF NOT EXISTS knowledge_chunks_embedding_idx "
        "ON knowledge_chunks USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100)"
    )
    op.create_table('agent_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_run_id'), 'agent_events', ['run_id'], unique=False)
    op.create_index('ix_agent_events_run_seq', 'agent_events', ['run_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_agent_events_user_id'), 'agent_events', ['user_id'], unique=False)
    op.create_table('outreach_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_drafts_user_id'), 'outreach_drafts', ['user_id'], unique=False)
    op.add_column('audit_traces', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('audit_traces', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_traces', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('audit_traces', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.create_index(op.f('ix_audit_traces_run_id'), 'audit_traces', ['run_id'], unique=False)
    op.alter_column('chat_messages', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tool_call_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tool_call_logs_run_id'), 'tool_call_logs', ['run_id'], unique=False)
    op.add_column('workflow_runs', sa.Column('lead_id', sa.String(), nullable=True))
    op.add_column('workflow_runs', sa.Column('final_result', sa.JSON(), nullable=True))
    op.add_column('workflow_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_workflow_runs_lead_id'), 'workflow_runs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_user_id'), 'workflow_runs', ['user_id'], unique=False)
    op.create_foreign_key('fk_workflow_runs_lead_id', 'workflow_runs', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema — drop Phase 1 tables and columns in reverse order."""
    # ── workflow_runs changes ──────────────────────────────────────────
    op.drop_constraint('workflow_runs_lead_id_fkey', 'workflow_runs', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_runs_user_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_lead_id'), table_name='workflow_runs')
    op.drop_column('workflow_runs', 'completed_at')
    op.drop_column('workflow_runs', 'final_result')
    op.drop_column('workflow_runs', 'lead_id')

    # ── tool_call_logs / audit_traces / chat_messages changes ──────────
    op.drop_index(op.f('ix_tool_call_logs_run_id'), table_name='tool_call_logs')
    op.drop_column('tool_call_logs', 'duration_ms')
    op.alter_column('chat_messages', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_audit_traces_run_id'), table_name='audit_traces')
    op.drop_column('audit_traces', 'cost_usd')
    op.drop_column('audit_traces', 'output_tokens')
    op.drop_column('audit_traces', 'input_tokens')
    op.drop_column('audit_traces', 'model_name')

    # ── Phase 1 new tables (reverse creation order) ───────────────────
    op.drop_index(op.f('ix_outreach_drafts_user_id'), table_name='outreach_drafts')
    op.drop_table('outreach_drafts')
    op.drop_index(op.f('ix_agent_events_user_id'), table_name='agent_events')
    op.drop_index('ix_agent_events_run_seq', table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_run_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.execute('DROP INDEX IF EXISTS knowledge_chunks_embedding_idx')
    op.drop_index(op.f('ix_knowledge_chunks_user_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_user_llm_config_user_id'), table_name='user_llm_config')
    op.drop_table('user_llm_config')
    op.drop_index(op.f('ix_user_embedding_config_user_id'), table_name='user_embedding_config')
    op.drop_table('user_embedding_config')
    op.drop_index(op.f('ix_user_email_config_user_id'), table_name='user_email_config')
    op.drop_table('user_email_config')
    op.drop_index('ix_leads_user_status', table_name='leads')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_knowledge_documents_user_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
