"""add mail workspace tables

Revision ID: 9a4f092a31fb
Revises: 7d8e9f0a1b2c
Create Date: 2026-09-04 20:58:06.047113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4f092a31fb'
down_revision: Union[str, Sequence[str], None] = '7d8e9f0a1b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('imap_uid', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('from_addr', sa.String(), nullable=False),
    sa.Column('to_addrs', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('trashed_at', sa.DateTime(), nullable=True),
    sa.Column('in_reply_to_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['in_reply_to_id'], ['mail_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mail_messages_user_dir_trashed', 'mail_messages', ['user_id', 'direction', 'trashed_at'], unique=False)
    op.create_index(op.f('ix_mail_messages_user_id'), 'mail_messages', ['user_id'], unique=False)
    op.create_table('mail_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('inbound_message_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('to_addr', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inbound_message_id'], ['mail_messages.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.ForeignKeyConstraint(['sent_message_id'], ['mail_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_drafts_user_id'), 'mail_drafts', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping knowledge_chunks_embedding_idx.
    # That pgvector IVFFLAT index is created via raw SQL (invisible to model
    # metadata), so dropping it here would silently break vector search. Trimmed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_drafts_user_id'), table_name='mail_drafts')
    op.drop_table('mail_drafts')
    op.drop_index(op.f('ix_mail_messages_user_id'), table_name='mail_messages')
    op.drop_index('ix_mail_messages_user_dir_trashed', table_name='mail_messages')
    op.drop_table('mail_messages')
    # ### end Alembic commands ###
